default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 220998
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: naitei_ruby_2020_airport_flight_management

test:
  <<: *default
  database: naitei_ruby_2020_airport_flight_management

production:
  <<: *default
  database: naitei_ruby_2020_airport_flight_management_production
  username: naitei_ruby_2020_airport_flight_management
  password: <%= ENV['NAITEI_RUBY_2020_AIRPORT_FLIGHT_MANAGEMENT_DATABASE_PASSWORD'] %>
