link:
  app:
    fontawesome: https://use.fontawesome.com/releases/v5.0.6/css/all.css
  layouts:
    sidebar:
      avatar: https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg
      alt_avatar: Avatar Admin
      size: 56
user:
  name_length: 50
  email_length: 255
  password_min_length: 6
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  default_password: "123456"
  default_staff_code: "11N2H1"
sessions:
  checkbox: "1"
  pattern: .{0}|.{6,20}
pagination:
  page: 7
notifications:
  readed: "1"
  no_read: "0"
  request:
    cancel_request: "3"
type_account:
schedules:
  format_date: "%Y - %B %e at %l:%M %p"
  format_time: "%Y-%m-%d %H:%M:%S"
requests:
  text_row: 5
  pilot: "pilot"
  air_traffic_officer: "air_traffic_officer"
  admin: "admin"
value:
  boolean: 1
  boolean_true: 1
  boolean_false: 0
channel:
  notifications: notifications_channel
type_account:
  pilot: 2
  air_traffic: 1
  admin: 0
status:
  notifications:
    view: 1
    unview: 0
  request:
    pending: 0
    approve: 1
    rejected: 2
    canceled: 3
runway:
  status: "0"
